import mysql.connector
from mysql.connector import Error

import mysql.connector

config = {
  'user': 'root',
  'password': '9010',
  'host': '127.0.0.1',
  'database': 'djangodb',
  'raise_on_warnings': True
}

cnx = mysql.connector.connect(**config)
cursor=cnx.cursor(named_tuple=True)
sql="select *from ajeet;"
cursor.execute(sql)
print(cursor.fetchone())



cnx.close()


